'use client';
import { useState } from 'react';
import { ArrowUpRight, Check, MapPin, Mail, MessageCircle, ShieldCheck, Wallet, Sparkles } from 'lucide-react';
import { benefits, categories, cities, faqs, site, socialLinks } from '@/lib/site-content';
import LocationMap from './location-map';

export default function SiteSections() {
  const [city, setCity] = useState('Raipur');
  return <>
    <section id="why" className="section content-section"><div className="section-heading"><div><span className="eyebrow">WHY CELEBRATECG</span><h2>One platform. Every celebration.</h2><p className="muted">A locally rooted platform, built around the way Chhattisgarh celebrates.</p></div></div><div className="value-grid">
      {[[ShieldCheck, 'Verified & curated', 'Local verification is planned for every stay and venue before launch.'], [Wallet, 'Transparent pricing', 'Upfront quotes for stays and services, so you can plan your celebration with clarity.'], [Sparkles, 'Payments at launch', 'UPI, cards and net-banking are planned as part of the launch booking experience.']].map(([Icon, title, description]) => { const Symbol = Icon as typeof ShieldCheck; return <article className="value-card" key={String(title)}><Symbol size={25} /><h3>{String(title)}</h3><p>{String(description)}</p></article>; })}
    </div></section>
    <section id="categories" className="section content-section"><div className="section-heading"><div><span className="eyebrow">EXPLORE CATEGORIES</span><h2>Stays, venues & services.</h2><p className="muted">Eight ways to make it memorable. Explore the categories and browse available venues.</p></div></div><div className="launch-category-grid">{categories.map((category, index) => <a className="launch-category" key={category.name} href="/#venues"><img src={`https://images.hostinger.com/${category.image}.png`} alt={category.name + ' in Chhattisgarh'} loading="lazy" /><div><span className="category-number">0{index + 1}</span><h3>{category.name}</h3><p>{category.description}</p><span className="category-action">Explore venues <ArrowUpRight size={15} /></span></div></a>)}</div></section>
    <section id="cities" className="section content-section city-section"><div className="section-heading"><div><span className="eyebrow">FEATURED CITIES</span><h2>Launching across Chhattisgarh.</h2><p className="muted">Properties onboarding in eight cities. Select a city to explore the area.</p></div></div><div className="city-map-grid"><div className="city-selector" aria-label="Choose a city for the map">{cities.map(name => <button key={name} className={city === name ? 'active' : ''} aria-pressed={city === name} onClick={() => setCity(name)}><MapPin size={18} /><span><strong>{name}</strong><small>Properties onboarding</small></span><ArrowUpRight size={16} /></button>)}</div><LocationMap location={`${city}, Chhattisgarh, India`} title={`Map of ${city}, Chhattisgarh`} note="City overview. This map does not indicate individual property locations." /></div></section>
    <section id="benefits" className="section content-section"><div className="section-heading"><div><span className="eyebrow">LAUNCH BENEFITS</span><h2>Built for guests, owners & partners.</h2><p className="muted">Planned launch benefits for guests, property owners and service partners.</p></div></div><div className="benefit-grid">{benefits.map(benefit => <article className="benefit-card" key={benefit.title}><h3>{benefit.title}</h3><ul>{benefit.items.map(item => <li key={item}><Check size={16} /><span>{item}</span></li>)}</ul><a className="text-button" href={benefit.title === 'Property owner benefits' ? '/signup?role=vendor' : benefit.title === 'Service partner benefits' ? '/#contact' : site.signup}>{benefit.title === 'Service partner benefits' ? 'Contact the team' : 'Create an account'} <ArrowUpRight size={15} /></a></article>)}</div></section>
    <section id="referral" className="section content-section referral-section"><div><span className="eyebrow">REFERRAL REWARDS · AT LAUNCH</span><h2>Invite friends.<br /><em>Earn celebrations.</em></h2><p>Planned for launch: invite friends, earn credits when they book, and redeem them on stays and event services.</p><a href={site.signup} className="button button-primary">Create an account <ArrowUpRight size={16} /></a></div><ol className="referral-steps">{[['Join the waitlist', 'Pick your list — guest, owner or service partner.'], ['Share your link', 'At launch, share with friends, family and WhatsApp groups.'], ['Friends book', 'They get founding-member pricing; you earn credits.'], ['Celebrate again', 'Redeem your credits on stays and services statewide.']].map(([title, description], i) => <li key={title}><span>0{i + 1}</span><div><h3>{title}</h3><p>{description}</p></div></li>)}</ol></section>
    <section id="waitlist" className="section content-section waitlist-section"><span className="eyebrow">PLAN • BOOK • CELEBRATE</span><h2>Your next celebration starts here.</h2><p>Create an account to find your next venue or list a space of your own.</p><a className="button button-primary" href={site.signup}>Create an account <ArrowUpRight size={16} /></a><small>Register and manage your account on this website.</small></section>
    <section id="faq" className="section content-section faq-section"><div><span className="eyebrow">A LITTLE CLARITY</span><h2>Questions, answered.</h2></div><div className="faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></section>
    <section id="contact" className="section content-section contact-section"><div className="section-heading"><div><span className="eyebrow">CONTACT</span><h2>Talk to the CelebrateCG team.</h2></div></div><div className="contact-grid"><div className="contact-info"><a href={site.whatsapp} target="_blank" rel="noopener noreferrer"><MessageCircle size={22} /><span><small>WHATSAPP</small>{site.phone}</span><ArrowUpRight size={16} /></a><a href={`mailto:${site.email}`}><Mail size={22} /><span><small>EMAIL</small>{site.email}</span><ArrowUpRight size={16} /></a><a href="https://www.google.com/maps/search/?api=1&query=Raipur%2C%20Chhattisgarh%2C%20India" target="_blank" rel="noopener noreferrer"><MapPin size={22} /><span><small>LAUNCH HQ</small>{site.headquarters}</span><ArrowUpRight size={16} /></a><div className="social-links">{socialLinks.map(([name, url]) => <a key={name} href={url} target="_blank" rel="noopener noreferrer">{name}<ArrowUpRight size={12} /></a>)}</div></div><LocationMap location={site.headquarters} title="CelebrateCG launch headquarters — Raipur, Chhattisgarh" note="Raipur city view. Contact the team for an exact meeting address." /></div></section>
  </>;
}
