'use client';
import { useState } from 'react';
import { ArrowUpRight, Check, MapPin, Mail, MessageCircle, ShieldCheck, Wallet, CreditCard } from 'lucide-react';
import { benefits, cities, faqs, platformOfferings, serviceProviders, site, socialLinks } from '@/lib/site-content';
import LocationMap from './location-map';

export default function SiteSections() {
  const [city, setCity] = useState('Raipur');
  return <>
    <section id="why" className="section content-section"><div className="section-heading marketplace-heading"><div><span className="eyebrow">WHY CELEBRATECG</span><h2>One platform. Every celebration.</h2><p className="muted">{site.introduction}</p></div></div><div className="value-grid">
      {[[ShieldCheck, 'Verified properties', 'Discover trusted properties with real photos and clear details before you book.'], [Wallet, 'Transparent pricing', 'Compare options by city, budget, guest capacity, stay and amenities with confidence.'], [CreditCard, 'Direct booking', 'Book with hosts and professional service partners from across Chhattisgarh.']].map(([Icon, title, description]) => { const Symbol = Icon as typeof ShieldCheck; return <article className="value-card" key={String(title)}><Symbol size={25} /><h3>{String(title)}</h3><p>{String(description)}</p></article>; })}
    </div></section>
    <section id="everything" className="section content-section offerings-section"><div className="section-heading"><div><span className="eyebrow">EVERYTHING YOU NEED</span><h2>For every kind of celebration.</h2><p className="muted">From finding the right setting to food, decor, entertainment and memories—bring the whole plan together with CelebrateCG.</p></div></div><div className="offerings-grid">{platformOfferings.map((offering, index) => <article className="offering-card" key={offering.title}><span>0{index + 1}</span><h3>{offering.title}</h3><p>{offering.description}</p></article>)}</div></section>
    <section id="services" className="section content-section service-providers-section"><div className="section-heading service-providers-heading"><div><span className="eyebrow">SERVICE PROVIDERS</span><h2>Book the people who make it happen.</h2><p className="muted">CelebrateCG brings venues and event-service partners together, so you can plan food, music, decor, mehndi, photography and production from one place.</p></div><a className="text-button" href="/categories#event-services">Explore services <ArrowUpRight size={15} /></a></div><div className="service-provider-grid">{serviceProviders.map(service => <article className="service-provider-card" key={service.title}><img src={service.image} alt={`${service.title} in Chhattisgarh`} loading="lazy" /><span className="service-provider-shade" aria-hidden="true" /><div><small>{service.tag}</small><h3>{service.title}</h3><p>{service.description}</p><a href="/#contact">Enquire now <ArrowUpRight size={14} /></a></div></article>)}</div></section>
    <section id="cities" className="section content-section city-section"><div className="section-heading"><div><span className="eyebrow">FEATURED CITIES</span><h2>Launching across Chhattisgarh.</h2><p className="muted">Properties onboarding in eight cities. Select a city to explore the area.</p></div></div><div className="city-map-grid"><div className="city-selector" aria-label="Choose a city for the map">{cities.map(name => <button key={name} className={city === name ? 'active' : ''} aria-pressed={city === name} onClick={() => setCity(name)}><MapPin size={18} /><span><strong>{name}</strong><small>Properties onboarding</small></span><ArrowUpRight size={16} /></button>)}</div><LocationMap location={`${city}, Chhattisgarh, India`} title={`Map of ${city}, Chhattisgarh`} note="City overview. This map does not indicate individual property locations." /></div></section>
    <section id="benefits" className="section content-section"><div className="section-heading"><div><span className="eyebrow">LAUNCH BENEFITS</span><h2>Built for guests, owners & partners.</h2><p className="muted">Planned launch benefits for guests, property owners and service partners.</p></div></div><div className="benefit-grid">{benefits.map(benefit => <article className="benefit-card" key={benefit.title}><h3>{benefit.title}</h3><ul>{benefit.items.map(item => <li key={item}><Check size={16} /><span>{item}</span></li>)}</ul><a className="text-button" href={benefit.title === 'Property owner benefits' ? '/signup?role=vendor' : benefit.title === 'Service partner benefits' ? '/#contact' : site.signup}>{benefit.title === 'Service partner benefits' ? 'Contact the team' : 'Create an account'} <ArrowUpRight size={15} /></a></article>)}</div></section>
    <section id="referral" className="section content-section referral-section"><div><span className="eyebrow">REFERRAL REWARDS · AT LAUNCH</span><h2>Invite friends.<br /><em>Earn celebrations.</em></h2><p>Planned for launch: invite friends, earn credits when they book, and redeem them on stays and event services.</p><a href={site.signup} className="button button-primary">Create an account <ArrowUpRight size={16} /></a></div><ol className="referral-steps">{[['Join the waitlist', 'Pick your list — guest, owner or service partner.'], ['Share your link', 'At launch, share with friends, family and WhatsApp groups.'], ['Friends book', 'They get founding-member pricing; you earn credits.'], ['Celebrate again', 'Redeem your credits on stays and services statewide.']].map(([title, description], i) => <li key={title}><span>0{i + 1}</span><div><h3>{title}</h3><p>{description}</p></div></li>)}</ol></section>
    <section id="waitlist" className="section content-section waitlist-section"><span className="eyebrow">PLAN • BOOK • CELEBRATE</span><h2>Your next celebration starts here.</h2><p>Create an account to find your next venue or list a space of your own.</p><a className="button button-primary" href={site.signup}>Create an account <ArrowUpRight size={16} /></a><small>Register and manage your account on this website.</small></section>
    <section id="faq" className="section content-section faq-section"><div><span className="eyebrow">A LITTLE CLARITY</span><h2>Questions, answered.</h2></div><div className="faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></section>
    <section id="contact" className="section content-section contact-section"><div className="section-heading"><div><span className="eyebrow">CONTACT</span><h2>Talk to the CelebrateCG team.</h2></div></div><div className="contact-grid"><div className="contact-info"><a href={site.whatsapp} target="_blank" rel="noopener noreferrer"><MessageCircle size={22} /><span><small>WHATSAPP</small>{site.phone}</span><ArrowUpRight size={16} /></a><a href={`mailto:${site.email}`}><Mail size={22} /><span><small>EMAIL</small>{site.email}</span><ArrowUpRight size={16} /></a><a href="https://www.google.com/maps/search/?api=1&query=Raipur%2C%20Chhattisgarh%2C%20India" target="_blank" rel="noopener noreferrer"><MapPin size={22} /><span><small>LAUNCH HQ</small>{site.headquarters}</span><ArrowUpRight size={16} /></a><div className="social-links">{socialLinks.map(([name, url]) => <a key={name} href={url} target="_blank" rel="noopener noreferrer">{name}<ArrowUpRight size={12} /></a>)}</div></div><LocationMap location={site.headquarters} title="CelebrateCG launch headquarters — Raipur, Chhattisgarh" note="Raipur city view. Contact the team for an exact meeting address." /></div></section>
  </>;
}
